/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */

export interface FormsUserCar {
  car_license?: string;
  car_name?: string;
  car_number?: string;
  cid?: number;
  driver_license?: string;
  uid?: number;
}
