/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { FormsUserCar } from './formsUserCar';

/**
 * 车辆信息数据
 */
export type FormsUserCarBody = FormsUserCar;
