/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */

export interface FormsProdCommentJson {
  comment_context?: string;
  comment_id?: number;
  comment_image?: string;
  comment_level?: number;
  comment_name?: string;
  prod_id?: number;
}
