/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { FormsProdSkuJson } from './formsProdSkuJson';

/**
 * 产品SKU数据
 */
export type FormsProdSkuJsonBody = FormsProdSkuJson;
