/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { FormsCategoryJson } from './formsCategoryJson';

/**
 * 产品种类数据
 */
export type FormsCategoryJsonBody = FormsCategoryJson;
