/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */

export interface FormsStoreInfoJson {
  store_addr?: string;
  store_bankcardname?: string;
  store_bankcardnum?: string;
  store_id?: number;
  store_image?: string;
  store_name?: string;
  store_ownner?: string;
  store_phone?: string;
  store_type?: number;
  user_id?: number;
}
