/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { FormsServiceJson } from './formsServiceJson';

/**
 * 服务种类数据
 */
export type FormsServiceJsonBody = FormsServiceJson;
