/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */

export interface FormsOrderSubmitInfo {
  pay_amount?: number;
  pay_method?: number;
  sku_id?: number;
  store_id?: number;
  user_id?: number;
}
