/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */

export interface FormsUserRegister {
  address?: string;
  age?: number;
  avatar?: string;
  city?: string;
  country?: string;
  email?: string;
  gender?: number;
  nickname?: string;
  password?: string;
  phone?: string;
  province?: string;
  role?: number;
  username?: string;
}
