/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { ModelsResUserInfo } from './modelsResUserInfo';

export interface FormsAuthLoginWx {
  code?: string;
  user_info?: ModelsResUserInfo;
}
