/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */

export interface FormsOrderUpdateInfo {
  order_id?: number;
  order_status?: string;
}
