/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { FormsProdJson } from './formsProdJson';

/**
 * 产品数据
 */
export type FormsProdJsonBody = FormsProdJson;
