/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { FormsProdCommentJson } from './formsProdCommentJson';

/**
 * 产品评论数据
 */
export type FormsProdCommentJsonBody = FormsProdCommentJson;
