/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { FormsProdStoreJson } from './formsProdStoreJson';

export interface FormsProdJson {
  brand_id?: number;
  category_id?: number;
  prod_comment_enable?: boolean;
  prod_desc?: string;
  prod_id?: number;
  prod_main_image?: string;
  prod_name?: string;
  prod_price?: number;
  prod_priority?: number;
  prod_status?: number;
  prod_stores?: FormsProdStoreJson[];
}
