/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */

export interface FormsProdImageJson {
  image_id?: number;
  image_type?: number;
  image_url?: string;
  prod_id?: number;
}
