/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */

export interface FormsProdSkuJson {
  prod_id?: number;
  sku_cost?: number;
  sku_discount?: number;
  sku_id?: number;
  sku_name?: string;
  sku_nums?: number;
  sku_price?: number;
  /** 对应ProdSpecLabel选项 0_1_2 代表3个选项中的对应索引 */
  sku_spec?: string;
}
