/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { FormsProdImageJson } from './formsProdImageJson';

/**
 * 产品image数据
 */
export type FormsProdImageJsonBody = FormsProdImageJson;
