/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */

export type GetApiV1ServiceCategoryProductListParams = { category_id?: string; page_num?: string; page_size?: string; status?: string };
