/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */

export type GetApiV1OrderListParams = { user_id?: number; store_id?: number; status?: string };
