/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { ModelsWXUserInfo } from './modelsWXUserInfo';

export interface ModelsResUserInfo {
  encryptedData?: string;
  iv?: string;
  rawData?: string;
  signature?: string;
  userInfo?: ModelsWXUserInfo;
}
