/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * carshop
 * carshop restapi server
 * OpenAPI spec version: 1.0
 */
import type { ModelsWatermark } from './modelsWatermark';

export interface ModelsWXUserInfo {
  avatarUrl?: string;
  city?: string;
  country?: string;
  gender?: number;
  language?: string;
  nickName?: string;
  openId?: string;
  province?: string;
  unionId?: string;
  watermark?: ModelsWatermark;
}
